services:
  elasticsearch:
    image: elastic/elasticsearch:8.16.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    restart: always
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local